services:
  - type: web
    name: riskx-backend
    env: python
    region: oregon
    plan: starter
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.api.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /api/v1/health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: riskx-postgres
          property: connectionString
      - key: PYTHON_VERSION
        value: "3.11"
      - key: ENVIRONMENT
        value: "production"
      - key: PYTHONPATH
        value: "."

databases:
  - name: riskx-postgres
    databaseName: riskx
    user: riskx_user
    plan: starter