#!/usr/bin/env python3
"""
Train ML Models for Supply Chain Risk Analysis

This script trains all ML models using the synthetic training data
generated by the generate_synthetic_training_data.py script.
"""

import sys
from pathlib import Path

# Add the app directory to Python path
sys.path.insert(0, str(Path(__file__).parent.parent))

from app.ml.supply_chain_models import SupplyChainMLPipeline

def main():
    """Train all ML models with synthetic data."""
    print("🔄 Starting ML model training...")
    
    # Create ML pipeline
    pipeline = SupplyChainMLPipeline()
    
    # Train all models (force retrain to use new synthetic data)
    print("\n📊 Training all supply chain ML models...")
    results = pipeline.train_all_models(force_retrain=True)
    
    # Display results
    print("\n✅ ML Model Training Complete!")
    print("📋 Training Results:")
    
    for model_name, metadata in results.items():
        if metadata:
            print(f"   - {model_name}:")
            print(f"     • Training data size: {metadata.training_data_size}")
            print(f"     • Trained at: {metadata.trained_at}")
            print(f"     • Version: {metadata.version}")
            if metadata.performance_metrics:
                for metric, value in metadata.performance_metrics.items():
                    print(f"     • {metric}: {value:.3f}")
        else:
            print(f"   - {model_name}: ❌ Training failed")
    
    print("\n🎯 Models are now ready for ML predictions!")

if __name__ == "__main__":
    main()